# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - rrr_arm_controller
    - rrr_hand_controller

  rrr_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
    action_ns: follow_joint_trajectory
    default: true
  rrr_hand_controller:
    type: GripperCommand
    joints:
      - gripper_joint_1
      - gripper_joint_2
    action_ns: gripper_cmd
    default: true