# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    rrr_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    rrr_hand_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

rrr_arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
rrr_hand_controller:
  ros__parameters:
    joints:
      - gripper_joint_1
      - gripper_joint_2