# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    rrrjointmoveitcontroller:
      type: joint_trajectory_controller/JointTrajectoryController


    rrrhandcontroller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

rrrjointmoveitcontroller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
rrrhandcontroller:
  ros__parameters:
    joint: gripper_joint_1